#!/bin/bash

# Remove all the files that are generated by the build process
rm -rf build
rm -rf */.cmake

# Remove the CMake cache
rm -rf */cg-generator
rm -rf */cg-engine
rm -rf */imgui.ini  

echo "Cleaned complete"