name: Validate code format with clang-format
on: [push, pull_request]
jobs:
  formatting-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: "*"
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check
      uses: jidicula/clang-format-action@v4.9.0
      with: 
        clang-format-version: "15"
        check-path: ${{ matrix.path['check'] }}
        exclude-regex: ${{ matrix.path['exclude'] }}
        fallback-style: "Google"